### ISSUE TITLE
Blackhole looks good, but event horizon causes issues

### ISSUE THREAD

**Issue by pccourt** [Pyxxilated-Studios/Blackhole#568]
Sending info in, but nothing is coming back...

**Describe the solution you'd like**
Please let me know an easy way to get hold of you and chat please :)

**Describe alternatives you've considered**
Smoke signals

**Comment by Pyxxil** [comment]
Are you still using your @ecogyenergy.com email?

**Comment by pccourt** [comment]
yes!

**Comment by Pyxxil** [comment]
See you in the fediverse (email sent)
